apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  labels:
    app: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: asia-south1-docker.pkg.dev/practice-assignment-gcp/shopnow/profile:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_URL
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo:27017/profileDB?authSource=admin"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: profile
  labels:
    app: profile
spec:
  type: ClusterIP
  ports:
  - port: 5002
    targetPort: 5002
    name: http
  selector:
    app: profile
